### ISSUE TITLE
Broken links & outdated note in Signal Reference documentation

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/Issues#200]
I just found that the "Session ID" and "Numerical Metrics" links at the bottom of this doc page seem to be broken:
https://telemetrydeck.com/pages/signal-reference.html

I also found this note which seems to be outdated (isn't that the default already):

> Note: In a future version of TelemetryDeck, you'll be able to [store signals locally in the app before sending them](https://github.com/TelemetryDeck/SwiftClient/issues/19). If you are using that technique, the server will no longer set the time the signal was created, but it will instead be set on the client.

I just found that when I wanted to request numerical payload fields as a feature, but then I found there that there already should be something somewhere, but I can't find something in the search here, would be great if you could point me to the discussion of that feature if any exists or I can create one.

**Comment by winsmith** [comment]
Thanks! Numerical metrics are coming at some later date. They're easy in principle, the problem is just we need to make sure the the format we choose is the right one, because once we publish a schema, we're more or less stuck with it.

Thanks for mentioning the outdated docs, we're on it! <3
